### ISSUE TITLE
Port update fails if Transmission password contains #

### ISSUE THREAD

**Issue by blackbunny208** [Michsior14/transmission-gluetun-port-update#38]
The mod works perfectly fine with a password set in the Transmission container environment, but fails if the password contains "#".  I ran a fresh container to generate the logs below, with the following options set in two different compose.yml.  The first one is with the password set in the environment, the second is with the password set in files.  The outcome is the same.

```
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1026
      - PGID=101
      - TZ=America/Los_Angeles
      - USER=blackbunny
      - PASS=abc1#efg2
      - DOCKER_MODS=linuxserver/mods:transmission-trguing|ghcr.io/michsior14/docker-mods:transmission-gluetun-port-update
    volumes:
      - /volume1/docker/transmission/config:/config
      - /volume1/data/Torrents:/Torrents
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped
```

```
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1026
      - PGID=101
      - TZ=America/Los_Angeles
      - FILE__USER=/config/user
      - FILE__PASS=/config/pass
      - DOCKER_MODS=linuxserver/mods:transmission-trguing|ghcr.io/michsior14/docker-mods:transmission-gluetun-port-update
    volumes:
      - /volume1/docker/transmission/config:/config
      - /volume1/data/Torrents:/Torrents
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped
```

In the example log below the username is "blackbunny" and the password is "abc1#efg2".  I am able to log into the Transmission web UI and even connect through RPC with this password, and the container works perfectly fine otherwise, but the port won't be updated, and the errors shown below appear.

```
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1026
User GID:    101
───────────────────────────────────────
[custom-init] No custom files found, skipping...
Installing transmission-gluetun-port-update
Connection to localhost (127.0.0.1) 9091 port [tcp/*] succeeded!
[ls.io-init] done.
2025/03/06 07:26:26 failed to parse transmission endpoint: parse "http://blackbunny:abc1": invalid port ":abc1" after host
transmission-gluetun-port-update already installed, skipping
2025/03/06 07:26:32 failed to parse transmission endpoint: parse "http://blackbunny:abc1": invalid port ":abc1" after host
transmission-gluetun-port-update already installed, skipping
2025/03/06 07:26:38 failed to parse transmission endpoint: parse "http://blackbunny:abc1": invalid port ":abc1" after host
```

If I simply remove the "#" from the password, it works just fine, and I'll just do that as a workaround, so I'm just letting you know about this.  I've tried a couple of other symbol characters, and they seem to work normally.
